name: Update Documentation

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório da documentação
        uses: actions/checkout@v4

      - name: Configurar Git
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'

      - name: Baixar e processar READMEs
        run: |
          mkdir -p docs/repos
          repos=$(jq -r '.repositories[] | "\(.org) \(.repo) \(.name)"' repos.json)
          for repo_info in $repos; do
            org=$(echo $repo_info | cut -d' ' -f1)
            repo=$(echo $repo_info | cut -d' ' -f2)
            name=$(echo $repo_info | cut -d' ' -f3-)
            echo "Baixando README de $repo da organização $org..."
            curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              -H "Accept: application/vnd.github.v3.raw" \
              "https://api.github.com/repos/$org/$repo/readme" -o "docs/repos/$repo.md" || echo "Falha ao baixar $repo"
          done

      - name: Commit e Push se houver mudanças
        run: |
          git add pages/mri/resources
          if git diff --cached --quiet; then
            echo "Sem mudanças, finalizando."
          else
            git commit -m "Atualização automática dos READMEs"
            git push
          fi
