name: Update Documentation

on:
  schedule:
    - cron: '0 0 * * *'  # Executa diariamente à meia-noite
  workflow_dispatch:  # Permite execução manual

jobs:
  update-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório da documentação
        uses: actions/checkout@v4

      - name: Configurar Git
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'

      - name: Baixar lista de repositórios
        run: |
          echo "Baixando lista de repositórios..."
          cat repos.json  # Apenas para depuração

      - name: Baixar e processar READMEs
        run: |
          mkdir -p pages/mri/resources
          jq -c '.repositories[]' repos.json | while read -r repo_info; do
            org=$(echo $repo_info | jq -r '.org')
            repo=$(echo $repo_info | jq -r '.repo')
            name=$(echo $repo_info | jq -r '.name')
            echo "Baixando README de $repo da organização $org ($name)..."
            curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              -H "Accept: application/vnd.github.v3.raw" \
              "https://api.github.com/repos/$org/$repo/readme" -o "pages/mri/resources/$repo.md" || echo "Falha ao baixar $repo"
          done

      - name: Commit e Push se houver mudanças
        run: |
          git add pages/mri/resources/
          if git diff --cached --quiet; then
            echo "Sem mudanças, finalizando."
            echo "no_changes=true" >> $GITHUB_ENV
          else
            git commit -m "Atualização automática dos READMEs"
            git push
            echo "no_changes=false" >> $GITHUB_ENV
          fi

      - name: Disparar outro workflow se houver mudanças
        if: env.no_changes == 'false'
        run: |
          curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
               -H "Accept: application/vnd.github.v3+json" \
               "https://api.github.com/repos/${{ github.repository }}/actions/workflows/deploy.yml/dispatches" \
               -d '{"ref":"main"}'
